name: update_gist
on:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: '2149da695c8eee57a662ad32fce4d1d0'
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
